# Generated by Django 5.2.4 on 2025-07-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0002_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='modelo',
            new_name='descripcion',
        ),
    ]
